### ISSUE TITLE
hello,1 bug ,please help

### ISSUE THREAD

**Issue by T8mars** [Nuked88/ComfyUI-N-Sidebar#1]
![QQ图片20240322000247](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/96167788/82e37957-ec4f-4cd0-9629-0bcaf09189fc)
![QQ图片20240322000406](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/96167788/2ad227af-2bd3-4fcb-bace-076e7f370a58)

The node is not displayed, it conflicts with these three plugins. Of course, there may also be other plugins, please try to fix it. Thank you

**Comment by Nuked88** [comment]
I will try to install those and see what i can do!

**Comment by T8star1984** [comment]
thanks!

**Comment by Nuked88** [comment]
Can you try now?

**Comment by T8star1984** [comment]
hello,it's okay!!Very well,thank for you nodes,it's great,I like it.Thanks again!
