### ISSUE TITLE
Search is completely broken after updating today

### ISSUE THREAD

**Issue by tetsuoo-online** [Nuked88/ComfyUI-N-Sidebar#102]
The sidebar became completely useless, only templates can be seen but nothing else, no nodes can be found anymore :/
I tried Original Normal or Fuzzy it makes no difference. Oh also the bar toggle works only if it's on Home icon.
Can I get previous version please ? It was very good, updating today has been a big mistake

**Comment by MrGingerSir** [comment]
same

**Comment by Nuked88** [comment]
please refer to this #100
