### ISSUE TITLE
The search list does not display any content

### ISSUE THREAD

**Issue by 807502278** [Nuked88/ComfyUI-N-Sidebar#103]
My environment: Win11, Google Chrome, Comfyui just updated today (20240802), python3.11 torch2.3.0+cu121
After updating this version of ComfyUI-N-Sidebar, the search list no longer displays anything,

9c9417622eb0f05bc4f1d56cce0a772f4f94a463

**Comment by newnaughty** [comment]
Same here

**Comment by rodsott** [comment]
For me it was happening last week.. now all the nodes are back. What disappeared today is the list of all my saved templates. Any idea of where they are stored, and if I can recover that list somehow, @Nuked88 ? I`m on Windows 10 using Chrome. I`ve tested on both MS Edge and Firefox and the templates as missing there as well. On those browsers the open menu on hover is not working, just on Chrome. Maybe something regarding with those CSS issues? Thanks in advance, and congrats for such useful tool! Hope it keep working on the new ComfyUI UI Frontend ^_^

**Comment by water110** [comment]
I also wondered where the template files were stored, I tried to find the installation directory and couldn't find it. I started to suspect that it was stored in the browser cache file or the system cache file, but after I uninstalled the plugin and cleared the browser cache file, I reinstalled it again and found that the previous template file was still there. (I tried to force delete the templates directly in the local folder since I was having problems with them not being able to be deleted, but I couldn't find the path)

**Comment by rodsott** [comment]
Ouch... I hope @Nuked88 could help us with this matter, which for myself is one of the most helpful features of his custom node.

**Comment by Nuked88** [comment]
Hi guys! The settings for the sidebar templates are stored in the **settings.json** file located in "custom_nodes\ComfyUI-N-Sidebar\app"
More specifically in the **sb_templateNodeMap** variable and in the **sb_ColorCustomTemplates** variable in case you used the function to color them.
There you can find the NAME of the templates, since I don't store the any templates, but comfyui does it in a  file called "comfy.templates.json," usually placed in the "ComfyUI\user\default" folder
To delete templates you have to use the context menu (right click) in the workflow and then do Node Templates > Manage
Unfortunately, I have not yet found any way to manage this from the sidebar :( @rodsott are the templates also gone from the comfyui context menu?

**Comment by Nuked88** [comment]
@807502278  @newnaughty did you tried with another browser?

**Comment by BannyLon** [comment]
升级到最新版后，自定义列表为空，且鼠标滑过侧边栏自动展开隐藏的功能失效。右键存为模版失效………………。折腾的我都准备放弃这个插件了，小错误真的很多很多。我的电脑是mac M2
![1722658994560](https://github.com/user-attachments/assets/ff7e1969-b0ad-4141-8960-e71a97b392ee)
![1722659025945](https://github.com/user-attachments/assets/ebe9c821-7fb2-4d34-b574-ff3d8348205e)

**Comment by Nuked88** [comment]
> 升级到最新版后，自定义列表为空，且鼠标滑过侧边栏自动展开隐藏的功能失效。右键存为模版失效………………。折腾的我都准备放弃这个插件了，小错误真的很多很多。我的电脑是mac M2 ![1722658994560](https://private-user-images.githubusercontent.com/140726408/354791811-ff7e1969-b0ad-4141-8960-e71a97b392ee.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NjEyNjMsIm5iZiI6MTcyMjY2MDk2MywicGF0aCI6Ii8xNDA3MjY0MDgvMzU0NzkxODExLWZmN2UxOTY5LWIwYWQtNDE0MS04OTYwLWU3MWE5N2IzOTJlZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QwNDU2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDlkMmFiOGRkNTk1NTc0MTQ0MDkxOTRjY2FiOTEyNDYxNGY1MDM4NDkzYjFjZGY2NzhlNzk4MTA0ODZiM2FjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VnhHUoEQspVdL7ED_3hEf4gIlO3EhVGWtUJqFqCmsYc) ![1722659025945](https://private-user-images.githubusercontent.com/140726408/354791812-ebe9c821-7fb2-4d34-b574-ff3d8348205e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NjEyNjMsIm5iZiI6MTcyMjY2MDk2MywicGF0aCI6Ii8xNDA3MjY0MDgvMzU0NzkxODEyLWViZTljODIxLTdmYjItNGQzNC1iNTc0LWZmM2Q4MzQ4MjA1ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QwNDU2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWFhMGJmOTk0NmU3ZGQ4YzNhNjY0NTJkZGFjYjhhMDUxZDU2ZjZiMmYwZGIyNDU4NmNmYzFkM2ZhMTNlM2FjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.07_uIzBf0i6a4TDUU2Q9VF6CoUrKglNaRQFZaULMI_I)

I'm sorry but before post this, did you tried another browser?

**Comment by BannyLon** [comment]
> > 升级到最新版后，自定义列表为空，且鼠标滑过侧边栏自动展开隐藏的功能失效。右键存为模版失效………………。折腾的我都准备放弃这个插件了，小错误真的很多很多。我的电脑是mac M2 ![1722658994560](https://private-user-images.githubusercontent.com/140726408/354791811-ff7e1969-b0ad-4141-8960-e71a97b392ee.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NjEyNjMsIm5iZiI6MTcyMjY2MDk2MywicGF0aCI6Ii8xNDA3MjY0MDgvMzU0NzkxODExLWZmN2UxOTY5LWIwYWQtNDE0MS04OTYwLWU3MWE5N2IzOTJlZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QwNDU2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDlkMmFiOGRkNTk1NTc0MTQ0MDkxOTRjY2FiOTEyNDYxNGY1MDM4NDkzYjFjZGY2NzhlNzk4MTA0ODZiM2FjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VnhHUoEQspVdL7ED_3hEf4gIlO3EhVGWtUJqFqCmsYc) ![1722659025945](https://private-user-images.githubusercontent.com/140726408/354791812-ebe9c821-7fb2-4d34-b574-ff3d8348205e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NjEyNjMsIm5iZiI6MTcyMjY2MDk2MywicGF0aCI6Ii8xNDA3MjY0MDgvMzU0NzkxODEyLWViZTljODIxLTdmYjItNGQzNC1iNTc0LWZmM2Q4MzQ4MjA1ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QwNDU2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWFhMGJmOTk0NmU3ZGQ4YzNhNjY0NTJkZGFjYjhhMDUxZDU2ZjZiMmYwZGIyNDU4NmNmYzFkM2ZhMTNlM2FjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.07_uIzBf0i6a4TDUU2Q9VF6CoUrKglNaRQFZaULMI_I)
> 
> I'm sorry but before post this, did you tried another browser?

我用的是Chrome浏览器，没有用其它浏览器测试。

**Comment by Nuked88** [comment]
> > > 升级到最新版后，自定义列表为空，且鼠标滑过侧边栏自动展开隐藏的功能失效。右键存为模版失效………………。折腾的我都准备放弃这个插件了，小错误真的很多很多。我的电脑是mac M2 ![1722658994560](https://private-user-images.githubusercontent.com/140726408/354791811-ff7e1969-b0ad-4141-8960-e71a97b392ee.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NjEyNjMsIm5iZiI6MTcyMjY2MDk2MywicGF0aCI6Ii8xNDA3MjY0MDgvMzU0NzkxODExLWZmN2UxOTY5LWIwYWQtNDE0MS04OTYwLWU3MWE5N2IzOTJlZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QwNDU2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDlkMmFiOGRkNTk1NTc0MTQ0MDkxOTRjY2FiOTEyNDYxNGY1MDM4NDkzYjFjZGY2NzhlNzk4MTA0ODZiM2FjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VnhHUoEQspVdL7ED_3hEf4gIlO3EhVGWtUJqFqCmsYc) ![1722659025945](https://private-user-images.githubusercontent.com/140726408/354791812-ebe9c821-7fb2-4d34-b574-ff3d8348205e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NjEyNjMsIm5iZiI6MTcyMjY2MDk2MywicGF0aCI6Ii8xNDA3MjY0MDgvMzU0NzkxODEyLWViZTljODIxLTdmYjItNGQzNC1iNTc0LWZmM2Q4MzQ4MjA1ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QwNDU2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWFhMGJmOTk0NmU3ZGQ4YzNhNjY0NTJkZGFjYjhhMDUxZDU2ZjZiMmYwZGIyNDU4NmNmYzFkM2ZhMTNlM2FjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.07_uIzBf0i6a4TDUU2Q9VF6CoUrKglNaRQFZaULMI_I)
> > 
> > 
> > I'm sorry but before post this, did you tried another browser?
> 
> 我用的是Chrome浏览器，没有用其它浏览器测试。

Try the incognito mode and see if this problem go away , if it does your just need to clear the cache or keep doing Ctrl+F5

**Comment by BannyLon** [comment]
> > > > 升级到最新版后，自定义列表为空，且鼠标滑过侧边栏自动展开隐藏的功能失效。右键存为模版失效………………。折腾的我都准备放弃这个插件了，小错误真的很多很多。我的电脑是mac M2 ![1722658994560](https://private-user-images.githubusercontent.com/140726408/354791811-ff7e1969-b0ad-4141-8960-e71a97b392ee.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NjEyNjMsIm5iZiI6MTcyMjY2MDk2MywicGF0aCI6Ii8xNDA3MjY0MDgvMzU0NzkxODExLWZmN2UxOTY5LWIwYWQtNDE0MS04OTYwLWU3MWE5N2IzOTJlZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QwNDU2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDlkMmFiOGRkNTk1NTc0MTQ0MDkxOTRjY2FiOTEyNDYxNGY1MDM4NDkzYjFjZGY2NzhlNzk4MTA0ODZiM2FjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VnhHUoEQspVdL7ED_3hEf4gIlO3EhVGWtUJqFqCmsYc) ![1722659025945](https://private-user-images.githubusercontent.com/140726408/354791812-ebe9c821-7fb2-4d34-b574-ff3d8348205e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NjEyNjMsIm5iZiI6MTcyMjY2MDk2MywicGF0aCI6Ii8xNDA3MjY0MDgvMzU0NzkxODEyLWViZTljODIxLTdmYjItNGQzNC1iNTc0LWZmM2Q4MzQ4MjA1ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QwNDU2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWFhMGJmOTk0NmU3ZGQ4YzNhNjY0NTJkZGFjYjhhMDUxZDU2ZjZiMmYwZGIyNDU4NmNmYzFkM2ZhMTNlM2FjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.07_uIzBf0i6a4TDUU2Q9VF6CoUrKglNaRQFZaULMI_I)
> > > 
> > > 
> > > I'm sorry but before post this, did you tried another browser?
> > 
> > 
> > 我用的是Chrome浏览器，没有用其它浏览器测试。
> 
> Try the incognito mode and see if this problem go away , if it does your just need to clear the cache or keep doing Ctrl+F5

感谢，感谢回复！我清除了缓存，删除了这个comfy.templates.json文件，重启了电脑，可以了。

**Comment by 807502278** [comment]
> @807502278 @newnaughty您尝试过使用其他浏览器吗？

Sure enough, it displayed normally when I changed the browser or cleared the browser cache.
