### ISSUE TITLE
possible to customize keyboard shortcuts

### ISSUE THREAD

**Issue by RONNYKHALIL** [Nuked88/ComfyUI-N-Sidebar#107]
i have option z mapped to my most used system wide shortcut (open Paste, for clipboard acccess). would love to know which file the code is in to change that on my personal setup (obv it would break when updating, but still curious to know!)

thanks!

btw, absolutely amazing work, and recent updates are HUGE for me. thanks for this indispensable custom node! keyboard shortcuts are super important to streamlining my work and any updates to add more shortcuts, like triggering specific templates etc, would be greatly appreciated!

**Comment by Nuked88** [comment]
Hi! If you want to edit manually those shortcuts you can edit the code here https://github.com/Nuked88/ComfyUI-N-Sidebar/blob/e911b5ca0de60312bb8b140cd94b17518865e926/app/js/sidebar_node.js#L938

**Comment by Nuked88** [comment]
OK, I've finally implemented custom shortcuts!

**Comment by RONNYKHALIL** [comment]
woohoo!
