### ISSUE TITLE
After last Update my sidebar broken

### ISSUE THREAD

**Issue by BlackVortexAI** [Nuked88/ComfyUI-N-Sidebar#108]
Since the last update my sidebar is not working properly. It no longer opens. Tested in Firefox, Brave and Chrome, my OS is Windows 11 Pro. Even with a completely fresh ComfyUI installation, the error persists. I have attached the console log from the browser, the terminal shows me no errors. I have also attached a picture of how it currently looks when unfolded.
![image](https://github.com/user-attachments/assets/e9076b8e-3f13-416e-990c-c3058539fa44)
![image](https://github.com/user-attachments/assets/6c27f5a3-a5ec-480b-84cf-0cab66135be3)

**Comment by lewionb** [comment]
Me, too. I get that question a lot

**Comment by terliu** [comment]
Me, too.+1

**Comment by Nuked88** [comment]
Hi, it looks like something related to the file that contains the templates in comfyui, I will check as soon as I can 😢

**Comment by BlackVortexAI** [comment]
> Hi, it looks like something related to the file that contains the templates in comfyui, I will check as soon as I can 😢 If you try to resize it using the mouse it doesn't work?

Hi thanks for your work. Unfortunately, I've only just got around to testing your template. Yes, your type works if you enlarge the bar when the “C” is displayed, it appears again and remains at the size even after a restart of the UI.

**Comment by lewionb** [comment]
Thank you, it worked, occasionally you can show the drag mouse zoom window logo, drag out

**Comment by Nuked88** [comment]
Ok, that should be fixed now: if there is no width dimension set, it will fall back to 200px.
