### ISSUE TITLE
Modify the top coordinate position and background transparency so that it does not conflict with components such as workspace!

### ISSUE THREAD

**Issue by DreamLoveBetty** [Nuked88/ComfyUI-N-Sidebar#13]
Modify the top coordinate position and background transparency so that it does not conflict with components such as workspace!
Please delete the attachment TXT suffix name
![20240324164829](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/138059406/a1096a20-6c7a-4aca-bbd0-9223bee097f9)
[sidebar_node.js.txt](https://github.com/Nuked88/ComfyUI-N-Sidebar/files/14734920/sidebar_node.js.txt)

**Comment by DreamLoveBetty** [comment]
[Uploading sidebar_node.js.txt…]()

**Comment by Nuked88** [comment]
Now you can edit that value directly from the ComfyUI Settings window!
