### ISSUE TITLE
Nice job! (+ some suggestions)

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [Nuked88/ComfyUI-N-Sidebar#16]
I just wanted to say cheers for making this.
The idea was on my todo-list, so thanks for saving me a bunch of time :D

The preview of the node is a brilliant touch!

A few suggestions / features that would improve the usability:

1. Being able to change the padding / spacing of the nodes and groups. They seem excessively thick right now and could certainly use some "Compact Mode" options. Ideally optional of course.
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/60541708/d79c939f-f4c8-4a9f-b60e-08c74f33f3d3)
Looking at the screenshot above you can see that I can only fit the "Adv-Controlnet" categories and "AnimateDiff" on my screen.

2. Having favorite (pinned nodes) is a good idea, but I wouldn't put them at the top as it is. I will easily put 20-50 nodes as favorite, and now my list will be even more cluttered. It's still a good idea, but what about making it a tab-like structure instead. So for your left-side-bar menu you still have the list as it is of Custom Nodes. These are just called "Nodes". And then there's a "Pinned" tab, where all my pins are.

3. And an even more relevant option for me would be to be able to build my own menu of nodes. Meaning I can create my own directory structure and pick nodes from all over the place, and then use that list as my master list of nodes. Essentially a "Pinned" tabs, but with more structuring options like categories/subcategories.

The largest issue I have with Comfy (aside from buggy UI), is that nothing is cohesive, since it's all extension driven. So there's no clean  way for me to sort all my "String related nodes" into one category. I want to pick bits and pieces of downloaded extensions, without having to manually copy the code into my own collection, that would be a nightmare to manage.

If Pinned nodes could be sorted into a tiered structure, or my #3 suggestion would work, then I think we're closer to having a reliable UI.

Sidenote:
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/60541708/0a58eb5d-6eb7-4353-862a-3f6a12ad13c0)
It doesn't play well with the [https://github.com/11cafe/comfyui-workspace-manager](Workspace Manager extension).

**Comment by Mike257art** [comment]
Excellent!!!

**Comment by Nuked88** [comment]
If you want to lower the bas just use the "[Sidebar] Space Top" in the ComfyUI option! :p and you can use the [Sidebar] Node Size for the point 1
I like the idea of a tab-like structure and even the custom category/node, what i dont really have is time right now so i will definetly try to do that, I just don't know when I will finish it 🤣

**Comment by MNeMoNiCuZ** [comment]
> If you want to lower the bas just use the "[Sidebar] Space Top" in the ComfyUI option! :p and you can use the [Sidebar] Node Size for the point 1 I like the idea of a tab-like structure and even the custom category/node, what i dont really have is time right now so i will definetly try to do that, I just don't know when I will finish it 🤣

One step ahead good sir!
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/60541708/e51695bc-1b35-4c65-b337-06cd9ed12d21)

Thanks, those settings worked perfectly for me :)

Don't stress about the feature suggestions.

But it could certainly add additional usability!
This has already made my week though <3

**Comment by Dog-brother0113** [comment]
Can you tell me how you made the picture you posted on Mar 25, 2024

**Comment by Nuked88** [comment]
Now I can close this since I've implemented the custom category option!
