### ISSUE TITLE
[feature request] Make use of the node description field

### ISSUE THREAD

**Issue by melMass** [Nuked88/ComfyUI-N-Sidebar#17]
Thanks for this extension.

Since [#1438](https://github.com/comfyanonymous/ComfyUI/pull/1438) we can add a `DESCRIPTION` field in python that can be leveraged in js (I'm implementing a side documentation panel based on that [here](https://github.com/melMass/comfy_mtb/pull/160))

It would be great to optionally display DESCRIPTION in the sidebar.

**Comment by Mike257art** [comment]
Genial!!!

**Comment by alessandroperilli** [comment]
I second this request. This sidebar with the node preview (thanks again for listening to my request on Reddit and implementing it) + the node description would be exceptional.

**Comment by Nuked88** [comment]
Ok, Description implemented! Even though I don't know any node that really uses it xD, but it supports HTML so it's pretty cool!
