### ISSUE TITLE
Great! It would be even better if the position could be adjusted. This way, it can harmonize with my other plugin.

### ISSUE THREAD

**Issue by wibur0620** [Nuked88/ComfyUI-N-Sidebar#2]
https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/131615326/4d968384-17b7-4d1c-a2ff-cba71e8c5006

**Comment by clayne** [comment]
Easy local hack for this btw:

Go to `sidebar_node.js` and edit this style:
```
        .sidebar {
            position: absolute;
            top: 0;
            left: -250px;
            left: -250px;
            width: fit-content;
            height: calc(100% - 19px);
            color: white;
            transition: left 0.3s ease;
			z-index: 2;
			padding-top: 19px;
            left: 0;
            user-select: none;

        }
```
Namely `top`. You can even do it with your browser's right click->inspect mode to check values first (try `top: 20px`).

**Comment by Nuked88** [comment]
Now you can edit that value directly from the [ ComfyUI Settings window](Now you can edit that value directly from the ComfyUI Settings window!)!
