### ISSUE TITLE
Preview not visible for nodes at the bottom 

### ISSUE THREAD

**Issue by alessandroperilli** [Nuked88/ComfyUI-N-Sidebar#20]
The preview for the nodes at the bottom of the sidebar is not completely visible:

<img width="1840" alt="Screenshot 2024-03-26 at 21 39 06" src="https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/9775949/31c51e53-caa6-4ce1-8fc2-66843c3a2edd">

I'm not sure if this is a technical issue that cannot be solved, or just a quirk of my browser (Vivaldi, on macOS).

Thank you for any help.

**Comment by Nuked88** [comment]
Fixed!
