### ISSUE TITLE
Love it, a few things I would like to see.....

### ISSUE THREAD

**Issue by getsmartt** [Nuked88/ComfyUI-N-Sidebar#23]
First off I just want to say this is absolutely brilliant, and is a great start to cleaning up the nodes in Comfy!

1.  Adjustable height, so my image stream docked at  the bottom doesn't cover part of this.
2.  Tokenized searching (already mentioned in another issue).
3.  A way to add/adjust node categories/groups  ( I think this has already been mentioned as well).
4.  Make the pinned area collapsable.
5.  An option to see nodes without their groups when searching..

I know you are a busy person and have created this without any obligation to implement suggestions, so I will likely take a look at a few of these myself when I have time.

**Comment by Nuked88** [comment]
Hi!
1 and 4 are easy to implement, so I think I will do it soon.
For the second point I already answered you in the other thread

For the others I will see what I can do since they are very good ideas anyway!

**Comment by Nuked88** [comment]
Ok, 1, 2, 4, and partially 5 have been implemented!

**Comment by Nuked88** [comment]
Ok i think that more or less i did everything now!
