### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Tobe2d** [Nuked88/ComfyUI-N-Sidebar#24]
Amazing work. Thank you!

Could you make option for the side bar to be on one of the sides (right or left) ?

**Comment by Nuked88** [comment]
Hi, thanks! Yes, as soon as I have time I will definitely do that!

**Comment by Tobe2d** [comment]
Awesome!

**Comment by amimi818** [comment]
> Hi, thanks! Yes, as soon as I have time I will definitely do that!

Could you add a shortcut to turn on/off the sidebar, thx？

**Comment by Nuked88** [comment]
Done!
