### ISSUE TITLE
新版本不支持中文搜索了，请问是以后都不支持了还是？

### ISSUE THREAD

**Issue by T8mars** [Nuked88/ComfyUI-N-Sidebar#25]
新版本不支持中文搜索了，请问是以后都不支持了还是？

**Comment by T8mars** [comment]
我不明白为什么忽然不支持中文了，之前都好好的

**Comment by Nuked88** [comment]
Uhm, I don't know either. Can you try to re-enable the normal search in the settings and tell me if it's working?

**Comment by T8mars** [comment]
My friend told me the new version don't support chinese serach,and I try to update it,I find the same problem.When I change the previous versions,the chinese search is right.please check it out.I'm very like this node!!!

**Comment by T8mars** [comment]
![QQ图片20240401174143](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/96167788/eaa3414d-072e-46ef-95c5-0201fed9ae4c)
you can see the picture,if I use chinese word search,it show nothing.but when I change the old version ,it run very well

**Comment by Nuked88** [comment]
I had to completely change the way it was searching to implement the fuzzy search. Before, it was searching directly in the HTML elements in the browser; now, it's searching in the ComfyUI node array.
But does the problem still occur even if you flag in the settings '[Sidebar] Use Default Search'?

**Comment by T8mars** [comment]
I will try it later,I will tell you result when I go home.

**Comment by T8mars** [comment]
The comfyui default node search don't support chinese very well,so you change the search method casue the node don't support Chinese,it maybe comfyui node search problem or conflict with other node.If it's terrilbe touble,I can change the version to date 28th March.This node is work well.Thanks

**Comment by Nuked88** [comment]
but, let me understand one thing, there is custom node with chinese name? or you use some kind of translator?

**Comment by wibur0620** [comment]
> but, let me understand one thing, there are custom nodes with chinese name? or you use some kind of translator?

![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/131615326/f5e56839-caa5-411d-bbb8-8afc255f63c0)
Everything is normal. If you cannot use Chinese for search, please uninstall the plugin mentioned in https://github.com/mape/ComfyUI-mape-Helpers/issues/14. To my knowledge, this plugin introduces fuzzy search for nodes, causing other language searches to fail. Additionally, the last maintenance by the plugin author was in February. Until this issue is fixed, continuing to use this plugin will render your plugin unable to perform searches in other languages. Currently, I confirm that uninstalling this plugin and opening the [Sidebar] Use Default Search option in settings allows for Chinese search. However, disabling the [Sidebar] Use Default Search option will disable searching in other languages. I believe you may have added the node fuzzy search feature and deliberately left the [Sidebar] Use Default Search setting to prevent other language searches from failing

**Comment by T8mars** [comment]
I found the node"[ComfyUI-mape-Helpers](https://github.com/mape/ComfyUI-mape-Helpers)" cause the official chinese search abnormal,but many chinese people use it,so I can't uninstall it.So I can use your node version 28th March,it's not conflict with it.thanks for you reply

**Comment by T8mars** [comment]
![QQ图片20240402114035](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/96167788/ba45021d-6470-49fc-9172-7e50632cef1e)
I ask other chinese users they all can't use new version for chinese search,they don't install ComfyUI_mape_helper nodes.So I don't know why that.I feel the problem is from new search method.

**Comment by T8mars** [comment]
I find the problem, the node "[ComfyUI-mape-Helpers](https://github.com/mape/ComfyUI-mape-Helpers)" conflict with your node new version.If we use the new version 31th. March,we need uninstall that node. and I need both modify setting about sidebar -use default search.So I change the 28th March version,it's ok.If ohter users say same problem,you can tell them this way

**Comment by Nuked88** [comment]
Thanks for the information! I'll put it in the readme as soon as I get home.
I still don't understand how you translate comfyui into Chinese (or if it's an automatic thing), can you clarify this for me?  So maybe I can try to get it working!

**Comment by T8star1984** [comment]
In china,the most people who use comfyui use the 秋叶akki comfyui package,download link:https://pan.quark.cn/s/64b808baa960
it automaticly translate the text to chinese.
And this code ‘https://github.com/mape/ComfyUI-mape-Helpers’ conflict with your new version ，it cause your node can't search in chinese
the way to use is change you node version to 27th.March

So,if you can't fix it,you can add a note,"if you can't search it in chinese,please change the old version 27th Marth " ,it can be done

**Comment by Sheng-Charles** [comment]
> Thanks for the information! I'll put it in the readme as soon as I get home.感谢您的信息！我一回家就会把它写进自述文件里。 I still don't understand how you translate comfyui into Chinese (or if it's an automatic thing), can you clarify this for me? So maybe I can try to get it working! 我仍然不明白你如何将 comfyui 翻译成中文（或者如果它是自动的），你能为我澄清一下吗？所以也许我可以尝试让它发挥作用！

Chinese users almost all use this node to translate: [**AIGODLIKE-COMFYUI-TRANSLATION**](https://github.com/AIGODLIKE/AIGODLIKE-COMFYUI-TRANSLATION)

**Comment by Nuked88** [comment]
Thanks guys for the explanation, I will try to see if it is possible to work with it!

**Comment by q1446227740** [comment]
Hello, if you can search in Chinese, please reply to me. I really need this feature

**Comment by q1446227740** [comment]
> 谢谢大家的解释，我会尝试看看是否可以使用它！

Hello, if you can search in Chinese, please reply to me. I really need this feature

**Comment by q1446227740** [comment]
> Thanks guys for the explanation, I will try to see if it is possible to work with it!

Hello, if you can search in Chinese, please reply to me. I really need this feature

**Comment by q1446227740** [comment]
> 新版本不支持中文搜索了，请问以后都不支持了还是？

哥们能分享一下之前的版本吗？我不知道咋下载之前的

**Comment by Nuked88** [comment]
Can you guys try now? You need to select "Original" in search type in the new option panel

**Comment by q1446227740** [comment]
> Can you guys try now? You need to select "Original" in search type in the new option panel

OK，I'll try updating the node

**Comment by aqidesign** [comment]
> Can you guys try now? You need to select "Original" in search type in the new option panel

I set search type is normal，search chinese is work. Thanks.
我在设置里将搜索类型设置为"normal"，可以搜中文了。

**Comment by q1446227740** [comment]
> > Can you guys try now? You need to select "Original" in search type in the new option panel
> > Thank you, changing SEARCN TYPE to "normal" can now search for Chinese normally

After setting up, click refresh a few times to search normally

**Comment by Nuked88** [comment]
Ok so I'm gonna close this, please reopen this issues if there are some other problem related to this!
