### ISSUE TITLE
click menu button, didn't  show up sidebar panel.

### ISSUE THREAD

**Issue by Erwin11** [Nuked88/ComfyUI-N-Sidebar#27]
### comfyui & n-sider is the lastest version.

![close](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/6300501/29dcdfbc-57a1-4528-96e8-ecc36e999b9f)

## after click
![open](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/6300501/15a31c52-b7ac-49a4-8c32-53d67f141c72)

**Comment by Erwin11** [comment]
edge is ok, chrome is broken.

**Comment by Nuked88** [comment]
Really weird, can you try to go in Application->LocalStorage->ComfyUI Address and delete the variable pinnedItems? 
Also clear the cookies and then retry!

**Comment by Erwin11** [comment]
It works!
I clearned up Local Storage, session Storage and cookies.
![40300](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/6300501/99593d7c-340e-4d21-9215-76d23fb8dff3)

chrome is my main browser, edge is backup, so they are less data in local storage.
