### ISSUE TITLE
可以增加一个功能吗？

### ISSUE THREAD

**Issue by 807502278** [Nuked88/ComfyUI-N-Sidebar#28]
原版的搜索可以从节点拉出连线来搜索，这样就能搜索与之相关的节点

比如说把连线拉到搜索栏的时候，显示所有和这根连线相关的节点，然后再在这些节点里搜索。
或许需要加一个按钮来切换：显示相关的节点/显示所有的节点

**Comment by Nuked88** [comment]
For that I should figure out how that thing actually works, although it doesn't always seem to work well since many times it leaves out important nodes. I'll keep it as a suggestion for the future!

**Comment by 807502278** [comment]
好，非常感谢
