### ISSUE TITLE
[Feature Request] Sorting subcategories 

### ISSUE THREAD

**Issue by toyxyz** [Nuked88/ComfyUI-N-Sidebar#3]
Thanks for the great work! 

Currently, if a particular custom node has multiple levels of categories, the categories inside are exposed to the outside.

It would be very useful if these subcategories could be collapsed!

![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/8006000/28d696b4-a4c6-4883-862a-8fd3201db3da)
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/8006000/d800f88b-24ce-4cdd-bac2-ad5598108837)

**Comment by toyxyz** [comment]
I think it would be more convenient to organize custom nodes that have multiple categories like this. 
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/8006000/a42751d5-fe8f-4421-85a3-439e95e5216e)

**Comment by toyxyz** [comment]
I think it would be more convenient to organize custom nodes that have multiple categories like this. 
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/8006000/18c65b88-9dc4-4eaf-a2af-e0d82476fea8)

**Comment by Dog-brother0113** [comment]
Can you tell me how you made the picture you posted on March 25, 2024

**Comment by Nuked88** [comment]
after like, forever, i did it!!

**Comment by toyxyz** [comment]
> after like, forever, i did it!!

Thank you very much! But the position of the search box is strange. 

![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/8006000/4d396715-3a45-4901-b443-eb13979da9bb)
