### ISSUE TITLE
Hope to add a feature

### ISSUE THREAD

**Issue by blueraincoatli** [Nuked88/ComfyUI-N-Sidebar#30]
The N-sidebar is a great node, I've talked to many comfyUI users, and we all want to have a way to clean up the duplicate nodes, is it possible to add a custom **hide/show** feature? Now the pin function is certainly helpful, but if we can hide the duplicate nodes and keep only the nodes we use frequently, it will keep comfyUI more cleaner and efficient.

**Comment by Nuked88** [comment]
Hi! I am working on an update that will lead to having categories created directly by users, this should solve this problem as well!

**Comment by Nuked88** [comment]
Custom categories: Done!
