### ISSUE TITLE
ComfyUI-N-Sidebar是一个很棒的功能，但在易用性上，是否多点选择和修改？

### ISSUE THREAD

**Issue by KennyChan3389** [Nuked88/ComfyUI-N-Sidebar#32]
1，我希望sidebar可以由用户设置在屏幕左边或者右边，以便贴近用户使用习惯。
2，我希望sidebar可以遵循原来的菜单结构分级，而不是现实一堆二级菜单，这对中文初学者并不友好。
3，我希望sidebar的置顶功能可以设置成置顶某个文件夹菜单，比如最近我正在学习ip-adapter，我其实是更希望整个文件夹菜单能够置顶，方便调用（而不是节点置顶）
总之，目前的sidebar对于中文学习者来说，方便，但是难于转换习惯，因为习惯问题我本人已经安装和卸载了无数遍。
我很喜欢这个插件，所以提出是否能够修改。

**Comment by Nuked88** [comment]
1 and 2 are done, 3 is a little more complicated  but i'll see what i can do!

**Comment by KennyChan3389** [comment]
> > 1 and 2 are done, 3 is a little more complicated but i'll see what i can do!
> 
> 谢谢您的工作，再回馈一下问题： 关于CUSTOM CATEGORIES，在面板中， 无法使用鼠标右键弹出菜单添加到自定义节点，我看了您在custom_categories.gif中的示例。

sorry，My mistake。
当sidebar在屏幕左边的时候，鼠标右键生效，且能看到预览图，

**Comment by Nuked88** [comment]
ok it should be fixed right now, can you try?

**Comment by Nuked88** [comment]
Hi! For the preview, can you try now?
For the structure you will have to wait a bit because it is not as easy as it seems (at least for me!)

**Comment by KennyChan3389** [comment]
> Hi! For the preview, can you try now? For the structure you will have to wait a bit because it is not as easy as it seems (at least for me!)

After testing, the preview problem was solved, but faced a new problem.
Some nodes inside a custom category can't be dragged and dropped to the workspace

![6818c449a106ea8a64d53d3aeaedfb36](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/155774773/8ebc80c0-5adc-482e-9275-c023dcf7e2c2)

settings.json
[settings.json](https://github.com/Nuked88/ComfyUI-N-Sidebar/files/15097071/settings.json)

**Comment by Nuked88** [comment]
can you try now 😓

**Comment by KennyChan3389** [comment]
After these few revisions, I deeply feel that it is not easy for the developers.
Thank you for doing all this!
It's worked out perfectly, thanks.
In the future, if I encounter any problems with the sidebar, I'll leave a comment here!

**Comment by Nuked88** [comment]
Thanks!

**Comment by KennyChan3389** [comment]
I'm here to trouble you again.
Can you make the sidebar top?
Right now it is.
<img width="282" alt="{6DDC8E55-9B31-4c07-9341-C739EADDA5CE}" src="https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/155774773/53bb1037-83da-4b3b-a666-1da4f65e1462">
If the sidebar is topped, it would work perfectly with the auto-hide feature.

**Comment by Nuked88** [comment]
Ok! Now you have a settings called z-index. If you increase that you can bring the sidebar on top!

**Comment by KennyChan3389** [comment]
Already in use. Thanks.

**Comment by KennyChan3389** [comment]
抱歉，我又来麻烦您了，
1，当侧边栏在右侧的时候，我发现节点预览也出现在节点右侧，这是不科学的。
2，Add to category的分类没有出现。
![af0b1674e49cf50298bc94128096756d](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/155774773/9227de03-508a-46c5-8f33-42c6c001156a)

**Comment by Nuked88** [comment]
Sorry for the late answer!
You just need to refresh the page once and it should work! I'm gonna close this issue now, if you have any other problem please open a new one!
