### ISSUE TITLE
The latest version of comfyui and ComfyUI-N-Sidebar seem to have compatibility problems

### ISSUE THREAD

**Issue by klossm** [Nuked88/ComfyUI-N-Sidebar#33]
The latest version of comfyui and ComfyUI-N-Sidebar seem to have compatibility problems, the N-Sidebar in the upper left corner cannot be displayed properly when clicked on, only ComfyUI-N-Sidebar is installed separately. other plugin conflicts have been ruled out.

**Comment by Nuked88** [comment]
Are you sure? Because it works fine for me with the latest version, can you give me a screenshot example?

**Comment by klossm** [comment]
> Are you sure? Because it works fine for me with the latest version, can you give me a screenshot example?

I'm sorry, it was a display problem caused by me accidentally dragging the box around the edge
