### ISSUE TITLE
Can this still be manually entered as before? Because some values want to be adjusted beyond the limit

### ISSUE THREAD

**Issue by 807502278** [Nuked88/ComfyUI-N-Sidebar#38]
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/46019416/e522ad4c-a1b6-4d67-9c8d-5f1803bd6b04)

Thank you very much. This makes the node very convenient to use

**Comment by Nuked88** [comment]
Hi! Yes, I still have to implement this feature, just curios, what's the limit that is too low for you?

**Comment by 807502278** [comment]
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/46019416/7d6b3aee-3429-41f9-8460-a23ba36a5a5d)
I want to reduce this to display more nodes

**Comment by Nuked88** [comment]
i've setted the minimum value to zero now!

**Comment by 807502278** [comment]
Thank you very much！
