### ISSUE TITLE
Could the plugin's edge width be narrower, please? Thank you.

### ISSUE THREAD

**Issue by Whatsk** [Nuked88/ComfyUI-N-Sidebar#42]
The new version's features are great, but there's too much unused width in the UI. 

When using it, especially with many nodes, there's already a lack of space. It's not very appropriate for the plugin to leave so much unused width at the edges. 

Below is a visualization of some of my ideas for the author's consideration. Thank you.

![side插件UI](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/79317284/070fa2ec-385c-4966-81d5-62d84457ceef)

**Comment by Nuked88** [comment]
given the change in sidebar design,I am closing this issue
