### ISSUE TITLE
can we have Saved Templates in the sidebar?

### ISSUE THREAD

**Issue by gamaraala666** [Nuked88/ComfyUI-N-Sidebar#44]
first things first, LOVE this plugin. 
but Im thinking this could be on steroids if we could have our saved templates in this as well with drag and drop. 

If its already possible,  could you please point the way?

**Comment by Nuked88** [comment]
For now, this is not possible, but it will be because it is one of the reasons why I created this plugin!

**Comment by Nuked88** [comment]
Done! (I've added workflows too!)
