### ISSUE TITLE
我无法使用这个插件，我在云服务器中安装的ComfyUI，安装这个插件后，页面没有任何修改。

### ISSUE THREAD

**Issue by zhu827995547** [Nuked88/ComfyUI-N-Sidebar#45]
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/136337433/9f104555-a5cc-4369-b4ba-678c57b0f446)
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/136337433/4cc4e6d3-9ad7-4c89-bac8-183e42e3cec1)

**Comment by Nuked88** [comment]
sadly this issue is not related to the sidebar! From your log all the javascript extensions cannot be fetched
