### ISSUE TITLE
[Function added] Added custom grouping function

### ISSUE THREAD

**Issue by idesign2018** [Nuked88/ComfyUI-N-Sidebar#46]
Pinned nodes can add multiple custom groups, such as common nodes, shortcut nodes and other functional groups for easy use.

![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/42263070/2de6a166-fe6e-4d68-bd2e-40e888d13b79)

**Comment by Nuked88** [comment]
the idea (which you'll see shortly) is to add more features there! At some point I would like to make the sidebar expandable but I'm not ready for that yet
