### ISSUE TITLE
Sidebar won't expand after update

### ISSUE THREAD

**Issue by yiwangsimple** [Nuked88/ComfyUI-N-Sidebar#51]
m1 max
![截屏2024-05-22 17 01 38](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/121092793/10568f19-855d-46ab-a9f2-67a92040559c)

**Comment by Nuked88** [comment]
to fix that you can use the **soft reset** button in the config!

**Comment by yiwangsimple** [comment]
I'm not sure where the soft reset button is that you're talking about, I've tried rebooting and refreshing and it doesn't do anything

**Comment by Nuked88** [comment]
click on the gear at the bottom

**Comment by yiwangsimple** [comment]
Thanks, I'll try again and see

**Comment by yiwangsimple** [comment]
&lt;img width="227" alt="Screenshot 2024-05-25 21 09 10" src="https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/121092793/147920ea-b080-4ba4- b133-8ddb2655660f">
I've tried over and over, and I think there's a conflict with this node.

**Comment by yiwangsimple** [comment]
<img width="227" alt="截屏2024-05-25 21 09 10" src="https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/121092793/8a8c9d77-fee5-433b-b5b9-37abae481704">

**Comment by yiwangsimple** [comment]
I've tried over and over, and I think there's a conflict with this node.

**Comment by Nuked88** [comment]
i don't know, i don't have that node
Try to disable it and let me know!

**Comment by yiwangsimple** [comment]
After disabling the node, the settings box popped up, tried a soft reboot, and it still doesn't show the node properly because you said a hard reboot would lose the node, so I didn't try it.

**Comment by Nuked88** [comment]
Press Ctrl + Shift + J to open the Developer Tools.
Then, go to the "Application" tab.
Under "Storage", expand "Local Storage" and select "http://127.0.0.1:8188/" (or the appropriate address if different).
Now, on the right side, you should see a list of variables with their respective values.
What's the value of sidebarWidth?

**Comment by Nuked88** [comment]
If you want, i've just pushed a new update, you can try use the soft reset again after the update to see if this time is working

**Comment by yiwangsimple** [comment]
Oh, great, it's working. Easy use, the missing node, is in conflict with this one, and I've deactivated it.

**Comment by yiwangsimple** [comment]
<img width="292" alt="截屏2024-05-25 23 08 11" src="https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/121092793/d5aa82d6-eca7-43b7-a0d8-207ed1d049f6">

**Comment by yiwangsimple** [comment]
extremely grateful
