### ISSUE TITLE
Latest pull doesnt show the new templates or workflows

### ISSUE THREAD

**Issue by Amorano** [Nuked88/ComfyUI-N-Sidebar#53]
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/225178/3cd5696c-a17d-44c9-a8f3-822041806713)

![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/225178/5c7f0eea-119e-4263-b12a-1322a64edfda)

![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/225178/e21e633c-b900-44fd-af1c-7d7dfb55be2d)

Fresh install of comfy, fresh install of manager, fresh install of Sidebar. You can see there are no icons for the new templates.

**Comment by Amorano** [comment]
Seems to work in Chrome, doesnt work in FF.

**Comment by Amorano** [comment]
No errors or warnings in console either.

**Comment by Amorano** [comment]
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/225178/ef21a366-f84a-41d1-8cdb-1f8f29b4f6ac)

got it.... halfway. Still no templates in the directory. I had to clear the cookies from the site. I assume you have some crusty old stuff in there someplace.

**Comment by Amorano** [comment]
> Cookie “pinnedItems” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
 

 That was the cookie that was messing it up.

**Comment by Amorano** [comment]
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/225178/b9229090-de40-4c06-a549-e5bcb2006fb9)

**Comment by Amorano** [comment]
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/225178/44b82f7e-5793-43a7-841b-d5b37931ef6a)


you do, indeed, need to add a "workflow" directory. That is not a thing; you should just make it if it doesnt exist.

**Comment by Nuked88** [comment]
yes! i'm fixing that right now, and since i was not using firefox i just notice that the layout is not working well there, so i'm tring to fix that too xD

**Comment by Amorano** [comment]
You should check opera as well -- lots of MAC users.

![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/225178/196aea09-1f7a-4acf-847a-adbe209a1a8b)

working okish now -- except I have sub-dirs, and it doesnt support those (yet I assume) -- and it should follow symlinks as well.

I assume you are using the ComyfyUI-Workspace-Manager as a outline: 
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/225178/b635917f-91e3-44e0-beb1-03c4838b0f68)

If it supported multilevel, then I think I can replace his with yours easy enough.

cheers!

**Comment by Nuked88** [comment]
Oh opera is working fine, is just firefox...
I will try to do multilevel and symlink!

**Comment by Nuked88** [comment]
Ok, now it should work fine in firefox

**Comment by Amorano** [comment]
verified issue resolved! cheers!
