### ISSUE TITLE
Feature Request: Click to Open Sidebar Option (instead of mouse-over)

### ISSUE THREAD

**Issue by camoody1** [Nuked88/ComfyUI-N-Sidebar#55]
Unless I'm missing something, the only way to have the sidebar configured is to open when moused-over. I would like to have an option to configure the sidebar to only open when one of the buttons is clicked (Home, Template, Workflow). As it works currently, I'm always accidentally opening it whenever I move my mouse off the active window to click on something else. It would be great to have an option for either mouse-over or click activation.

Thank you for your great addition to ComfyUI.

**Comment by toyxyz** [comment]
I think it would be nice to be able to use shortcuts to open the sidebar!

**Comment by Nuked88** [comment]
Yes, i will implement that for sure!

> I think it would be nice to be able to use shortcuts to open the sidebar!

https://github.com/Nuked88/ComfyUI-N-Sidebar?tab=readme-ov-file#keyboard-shortcuts

**Comment by nodegraphics** [comment]
I love the Sidebar. Thank you !! It helps me a lot. 
I came to request the same feature and it was already opened. 
Option to disable the mouse-over feature, as it would be very helpful, especially when using multiple monitors.

**Comment by camoody1** [comment]
> Yes, i will implement that for sure!
> 
> > I think it would be nice to be able to use shortcuts to open the sidebar!
> 
> https://github.com/Nuked88/ComfyUI-N-Sidebar?tab=readme-ov-file#keyboard-shortcuts

I'm not necessarily talking about a keyboard shortcut. I was thinking more of an option to keep the sidebar docked (and visible) along the side of the screen until the user clicks one of the visible buttons.
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/73725653/3d3b550e-e4ef-467f-8c73-6707bf149f7e)

**Comment by Maya-China** [comment]
I really hope that the five icons in the sidebar can expand their respective content by clicking, rather than hovering. Due to the hovering and unfolding method, these 5 icons ran from the left to the right. To select them, it was quite tiring to move the mouse back and forth.

**Comment by camoody1** [comment]
I'm just hoping the change comes sooner than later. I'm about to uninstall the extension just due to how annoying it is every time I move my mouse off the window to click on something else. I love the extension, but it's driving me crazy. 😂

**Comment by camoody1** [comment]
> DONE!

Perfection! Thank you so much!
