### ISSUE TITLE
I get an error that the workflows folder does not exist.

### ISSUE THREAD

**Issue by Enchante503** [Nuked88/ComfyUI-N-Sidebar#56]
```
ComfyUI-N-Sidebar/__init__.py", line 117, in s_get
    for entry in os.scandir(list_workflows):
FileNotFoundError: [Errno 2] No such file or directory:
```
I get an error that the workflows folder does not exist.
There seems to be a problem with how to get the Workflow folder.

**Comment by Nuked88** [comment]
Did you set the workflow dir in the settings?

**Comment by Nuked88** [comment]
I am closing this topic because there have been no responses in the last 24 hours, please reopen it if you indeed continue to have the problem.

**Comment by Nuked88** [comment]
is correct if you don't hae templates, custom category and workflows xD

**Comment by Nuked88** [comment]
is just the gear at the bottom
