### ISSUE TITLE
Confused about the Workflow library feature

### ISSUE THREAD

**Issue by alessandroperilli** [Nuked88/ComfyUI-N-Sidebar#57]
First of all, thank you for expanding the Sidebar capabilities to support both templates and workflow libraries. It's a great addition.

While the Template library works fine, I'm really struggling with the Workflow library. I have the following issues:

1. If I do NOT specify a custom folder in the Sidebar settings, and I save a workflow, the name of the workflow is correctly stored in the `settings.json`, but the actual workflow is nowhere to be found in the hard drive. 

To double-check, after saving the workflow, I clear the canvas and try to drag and drop one of the saved workflows from the Sidebar. Nothing happens.

What is the default location of saved workflows if no custom folder is indicated? 
AFAIK, no default path for workflows can be defined in ComfyUI's `extra_model_paths.yaml`, so I am not sure where to look, and a `where` command returns no results.

2. If I DO specify a custom folder in the Sidebar settings (for example: D:\Workflows), and I restart ComfyUI as indicated, the path is ignored. Saving a new workflow doesn't generate a json file in there as I'd expect.

Notice that the ComfyUI server is on a Windows machine and I access it via macOS over a HTTPS session.

Thanks for you help.

**Comment by Nuked88** [comment]
If you do not specify the folder, the sidebar will look for the workflow in the worflows folder within the ComfyUI folder (this is just a convention, because that folder usually does not exist).
Do you get any errors in the console?

**Comment by alessandroperilli** [comment]
In fact, in my installation, I don't have any /workflow/ folder. 

I see no error in the console: either when I save the workflow, or when I try to drag the workflow, or when I set a custom folder where to save the workflows, or when I restart ComfyUI and the sidebar looks for that custom folder.

**Comment by Nuked88** [comment]
uhmm I am quite confused about your situation, 
I am really struggling to understand "If I do NOT specify a custom folder in the Sidebar settings, and I save a workflow, the name of the workflow is correctly stored in the settings.json, but the actual workflow is nowhere to be found in the hard drive.”
I am not managing any “saving workflow”.
are you Italian/do you speak Italian? 
Maybe in my native language I can understand the situation better.

**Comment by Nuked88** [comment]
Now I understand. There is a misunderstanding: the sidebar is not able to save a workflow. You need to use the usual SAVE button of ComfyUI. I don't know if I will implement a save feature since it would be like having two save buttons on the same interface, even if I must admit that choosing the path where to save every time is really annoying.

The + button is for adding categories, like in the Custom Category and Template panels. I will add a snippet to make that clear soon.

**Comment by alessandroperilli** [comment]
But then, if it doesn't save the workflows, what does it do? 

Does it point to existing workflows (wherever they are in the disk) and allow you to organize them in categories?

**Comment by Nuked88** [comment]
Yes, it allows you to rename/remove and categorize them. And to load them on the fly by dragging them to the main panel.

**Comment by alessandroperilli** [comment]
I see. It's confusing to depend on another system for saving (I use pythongosssss Custom Scripts for saving the workflows), and on the Sidebar for managing them. But now I understand. Thank you for taking the time to explain this to me.
