### ISSUE TITLE
[Feature Request] Customizable sidebar expansion behavior

### ISSUE THREAD

**Issue by alessandroperilli** [Nuked88/ComfyUI-N-Sidebar#58]
The sidebar is incredibly useful to me, but it tends to be in the way a lot while dragging the canvas.

At the beginning, when it was just a tiny burger icon in the top left corner, it was much easier. No matter how much canvas dragging, there was practically never the chance to trigger it.

However, since the tiny burger icon evolved into a full column (no matter how thin when minimized), I accidentally expand it 100 times a day. 
It happens so often that a number of AP Workflow users asked me how to permanently delete it. 

It would be ideal if we could optionally configure the sidebar to appear as a single icon in the top left corner of the screen, as it was originally.

If that's not possible, it would be useful if we could set a custom timeout in the settings, so that the sidebar minimizes much faster than now.
Or in a way that it expands only if the mouse hovers above it for a much longer time.

Thank you for considering these ideas.

**Comment by Nuked88** [comment]
This topic is already being covered [here] (https://github.com/Nuked88/ComfyUI-N-Sidebar/issues/55), so I am closing this.
