### ISSUE TITLE
Where is the custom related data saved?

### ISSUE THREAD

**Issue by wuqq** [Nuked88/ComfyUI-N-Sidebar#59]
N-Sidebar is a great feature and I really like this feature.

In addition, I want to know where the Custom Categories and Templates set in the N-Sidebar are stored.
Because I want to be able to use this custom data when changing devices or sharing it with friends.
Support for import and export is even better.

**Comment by Nuked88** [comment]
Hi, it's in the /custom_nodes/ComfyUI-N-Sidebar/app/settings.json

**Comment by wuqq** [comment]
> Hi, it's in the /custom_nodes/ComfyUI-N-Sidebar/app/settings.json

Thank you very much. 
When I opened this JSON file, I took a look at it, but it was ignored because there was no data in it. 
I think sb_templateNodeMap should have a separate JSON file to manage it.

**Comment by Nuked88** [comment]
single settings export implemented! 2c08bb7
