### ISSUE TITLE
Small improvements

### ISSUE THREAD

**Issue by belenkoksas** [Nuked88/ComfyUI-N-Sidebar#6]
From screen:
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/7004034/3a707e28-bce7-422b-b01a-e29b50e09149)

i customized to this i believe in more compact:
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/7004034/d395958c-f567-4db1-b6d7-889500900d94)
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/7004034/9946c4b5-9102-49cb-8a88-7e0a53e802b3)

and i can use explorer search with expanded all adons list, i love this new workflow:
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/7004034/ee2e0fc7-36e2-4fce-bec4-7a8462f385ff)

**Comment by Nuked88** [comment]
Now you can edit those values directly from the [ ComfyUI Settings window](https://github.com/Nuked88/ComfyUI-N-Sidebar?tab=readme-ov-file#-custom-values-from-comfyui-settings-)
