### ISSUE TITLE
中文版本下无法使用中文进行搜索

### ISSUE THREAD

**Issue by Chadli2022** [Nuked88/ComfyUI-N-Sidebar#63]
中文版本下无法使用中文进行搜索,可以正常使用但无法使用中文搜索!

**Comment by Nuked88** [comment]
even with the search type setted on ORIGINAL?

**Comment by dxyklp** [comment]
俺也一样，你解决没

**Comment by Nuked88** [comment]
i need to know if are you using the ORIGINAL search 
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/1554140/77e45949-71e8-4fdd-9cff-f2ac161dc6bc)

**Comment by dxyklp** [comment]
> 我需要知道您是否正在使用原始搜索 ![image](https://private-user-images.githubusercontent.com/1554140/337422187-77e45949-71e8-4fdd-9cff-f2ac161dc6bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MDQ5MzIsIm5iZiI6MTcxNzcwNDYzMiwicGF0aCI6Ii8xNTU0MTQwLzMzNzQyMjE4Ny03N2U0NTk0OS03MWU4LTRmZGQtOWNmZi1mMmFjMTYxZGM2YmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMjAxMDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzlhYzdkMmJkZmRkNWE2NWQ3Mzc3Njk1OTgzZWUxYjk5MWM1ZGJjZDZmNDZhNTlkMzUyMDc3YWY1YzFiYjVjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ajBv3iyn8Bkb3c6Y0ce-x_51yOo71nt2qLao9GGezcw)

感谢你的解答，之前版本我好像使用的是[FUZZY],在最新版本里我依然使用它，这导致了我无法用中文搜索，按照你的说法，我换到了[ORIGINAL]的搜索方式，已经可以正常使用了
