### ISSUE TITLE
Click on the icon and keep the 5 icons fixed on the left side

### ISSUE THREAD

**Issue by Maya-China** [Nuked88/ComfyUI-N-Sidebar#64]
1. I really hope that the five icons in the sidebar can expand their respective content by clicking, rather than hovering. Due to the hovering and unfolding method, these 5 icons ran from the left to the right. To select them, it was quite tiring to move the mouse back and forth.

2. Don't move the 5 icons, keep them from the left, and the expanded content will appear on the right by clicking, which will be very easy.

**Comment by Nuked88** [comment]
are you a wizard? I've started to do the point 2 yesterday xD

**Comment by Nuked88** [comment]
done!

**Comment by Maya-China** [comment]
Thank you for your update. It was great. I received feedback yesterday and it was fixed today. The experience is fantastic now. A very good plugin, it is very fast and convenient to find nodes and workflows.
