### ISSUE TITLE
Chrome missing nodes in list?

### ISSUE THREAD

**Issue by taconugget** [Nuked88/ComfyUI-N-Sidebar#65]
Chrome is missing all the nodes for some reason today? Works in safari fine. I tried reinstalling the node, and clearing the browser cache.. anything else I should try??

Updated Chrome Today :(
Version 125.0.6422.142 (Official Build) (x86_64)

<img width="1405" alt="Screenshot 2024-06-04 at 11 36 05 AM" src="https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/22509743/cd1581e5-0b41-47e9-bece-e4b6a33d129a">

**Comment by Nuked88** [comment]
uhm i just update chrome but i did not have any issues, maybe there is something corrupted? Try to to open the feveloper console from The settings -> more tools -> Developer Tools. Then go in the console tab and show me what you see

**Comment by taconugget** [comment]
Im on a Mac so this console is a little different area. Hopefully this is what you wanted. Thx for the help Nuked!
<img width="554" alt="Screenshot 2024-06-04 at 12 58 40 PM" src="https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/22509743/314178d5-7678-4311-b879-2bb12addb64c">

**Comment by taconugget** [comment]
a blank white page...

I went and checked the file on the linux server here /home/name/ComfyUI/user/default/comfy.templates.json and its a blank file as well. With that said Ive never installed or made any templates so maybe this is normal?

**Comment by Nuked88** [comment]
well yeah, if is not reporting any error it should work anyway!

**Comment by taconugget** [comment]
It was working in every other browser I have, Firefox, Brave, Safari. I went ahead and blew out the Cache again now its working. Really great tool Nuke. Thx for the help today sir!
