### ISSUE TITLE
[BUG] Sidebar visibility state not saved when browser is refreshed/reloaded

### ISSUE THREAD

**Issue by tajino** [Nuked88/ComfyUI-N-Sidebar#70]
When the browser is reloaded, the Sidebar expanded panel will always appear regardless of the previous state it is in.

Steps to recreate the issue :
1. click the 'Toggle sidebar' button (3 lines icon) to collapse it, 
2. reload the page, the expanded sidebar will appear again.

If it is not practical to the save sidebar visibility toggle state on each sidebar toggle click, I would suggest having an option for the initial visibility state of the sidebar, "Show sidebar on start", boolean checkbox, if uncheck, the sidebar will always be collapse on first init when browser page is reloaded.

Hope you can look into it. Thanks.

**Comment by Nuked88** [comment]
Hi, actually the state is saved! When you reload the page and you previously selected that the bar was collapsed, it will appear open until you click somewhere on the screen. The only thing I can change is that behavior

**Comment by tajino** [comment]
I noticed that too after using it for while, it appears to be open but actually it is not. Would be great if you could change the current behavior, it is pretty misleading looking like it is opened and trying to close it by clicking the toggle button and ended up opening it instead.

**Comment by Nuked88** [comment]
This has been fixed, I forgot to close it!
