### ISSUE TITLE
Setting button doesn't show up at the bottom

### ISSUE THREAD

**Issue by nodegraphics** [Nuked88/ComfyUI-N-Sidebar#71]
Hello,
After i installed the sidebar i wont be able to see the settings button at the bottom. I tried to change the zoom in/out setting in browser but still no luck. The height of the sidebar extends and i believe doesn't show up

![Screenshot - 2024-06-16 22 19 01](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/10071439/251ac989-6d01-41ef-92d8-a3c8330620f4)

**Comment by Nuked88** [comment]
Use Alt+G to open the settings panel
