### ISSUE TITLE
Overlap problem with "easy use" custom node

### ISSUE THREAD

**Issue by nodegraphics** [Nuked88/ComfyUI-N-Sidebar#72]
[Easyuse ](https://github.com/yolain/ComfyUI-Easy-Use)custom nodes overlaps with setting button. i cant change the z depth because i cant open sidebar settings.

![sidebar_save](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/10071439/55af70dc-3048-44f5-a803-55c818242d74)

**Comment by Nuked88** [comment]
Use Alt+G to open the settings panel
