### ISSUE TITLE
hi,I need you help,thanks

### ISSUE THREAD

**Issue by T8star1984** [Nuked88/ComfyUI-N-Sidebar#75]
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/161950228/49605aae-a40f-49a5-9108-c35cdd069090)
![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/161950228/9a0ea11a-3d62-4fdd-9363-c54adec3ff74)
Hi,Can you move the setting button to the side bar.Some node cover it causing that I can't modify the setting.

**Comment by Nuked88** [comment]
In that case use Alt+G to open the settings!
