### ISSUE TITLE
"TEMPLATES" can only be used once!

### ISSUE THREAD

**Issue by HaoJingang** [Nuked88/ComfyUI-N-Sidebar#81]
The templates I have saved in TEMPlates can only be used once. When I drag them out and then drag them from inside out, there is no response; Also, if I delete a template that has already been dragged out, there will be no response when I drag it again. That is to say, when I need to use the same node template multiple times, I cannot use it, which is not very user-friendly for calling large workflows. I hope the author can support multiple calls to the same template.
![微信图片_20240705104038](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/96185634/01308cdc-92d3-4c07-8461-a68606ae9609)

**Comment by HaoJingang** [comment]
I have this issue using both browsers, one is Microsoft Edge and the other is Google Chrome.

**Comment by Nuked88** [comment]
Should be fixed right now!
