### ISSUE TITLE
部分节点显示PREVIEW NOT AVAILABLE

### ISSUE THREAD

**Issue by BannyLon** [Nuked88/ComfyUI-N-Sidebar#83]
ComfyUI-N-Sidebar升级了最新，但是在鼠标滑过节点时，部分节点显示PREVIEW NOT AVAILABLE，我不知道问题出在哪里？我的电脑是MAC M2，请教各位，感谢！
![1720519852129](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/140726408/aab235b7-a5bf-4dbd-949b-0aec51aa4551)

**Comment by Nuked88** [comment]
Hi! It is normal for javascript-only nodes, as I have not yet found a way to generate their preview.
