### ISSUE TITLE
1 bug,please help

### ISSUE THREAD

**Issue by T8mars** [Nuked88/ComfyUI-N-Sidebar#84]
![image](https://github.com/user-attachments/assets/2a56d83d-61b0-4821-a22b-7f1905467abb)
Whatever I input,it happen nothing.I try to modify the normal, fuzz,etc model,but the result is same.

**Comment by Nuked88** [comment]
Since you are using Chinese language you should use "Original" anyway, then there could be some incompatibility from some node that are you using. Can you show me the developer console log after you try to search? But first remember to put "Original" in the setting and refresh the page!

**Comment by T8mars** [comment]
okay,please wait

**Comment by T8mars** [comment]
![D91339A7A828905476DE94D1247CC668](https://github.com/user-attachments/assets/8ff43388-9f56-415c-9f39-a2e47a327fde)
I use the original mode,and refresh the page,I input the "string"to the inputbox,and click the button,but it happen nothing

**Comment by T8mars** [comment]
![Uploading 1E1EE95E1C3994616D239841A0C73B69.png…]()

**Comment by T8mars** [comment]
I have solve the problem ,thanks for your help
