### ISSUE TITLE
Bǎocún múbǎn hé bǎocún gōngzuò liú shīxiào 12 / 5,000 Save template and save workflow fail

### ISSUE THREAD

**Issue by sebord** [Nuked88/ComfyUI-N-Sidebar#85]
When I save the template according to the readme and click refresh, the template I saved is not there
![image](https://github.com/user-attachments/assets/fd89f6ca-936f-4ae7-b8c8-bddba113edf2)

**Comment by Nuked88** [comment]
Hi! You should be more specific about what you are using (OS, browser, local/remote install...) and if there are any errors in the developer console if you want help, otherwise it's pretty impossible to know what's going on!
