### ISSUE TITLE
Mac - alt (which is option key) keys don't work

### ISSUE THREAD

**Issue by scruffynerf** [Nuked88/ComfyUI-N-Sidebar#89]
Added Sidebar, and couldn't find the settings.  Read issues, and learned that alt-g was the way to open it.  Except no key combo (which should be option-G) worked, on 2 different browsers (Firefox and Brave), on MacOS
modified:
```
function handleKeyPress(event) {
    if (event.altKey 
```
events to:
```
function handleKeyPress(event) {

    if (event.ctrlKey 
```

and it worked with ctrl-G.  So please add an alternative choice to 'alt', which doesn't seem to work on Macs, despite that it should.

**Comment by Nuked88** [comment]
Hi! Can you try now ( with the option key )?

**Comment by scruffynerf** [comment]
> Hi! Can you try now ( with the option key )?

Yes.  v1.2.3 fixes it.  Thanks!
