### ISSUE TITLE
Whether it can be turned on/off automatically by hovering over the mouse  

### ISSUE THREAD

**Issue by amimi818** [Nuked88/ComfyUI-N-Sidebar#9]
It is suggested that it can be turned on/off by hovering over the mouse, just like lobehub in A1111

![image](https://github.com/Nuked88/ComfyUI-N-Sidebar/assets/133093934/5d95ac7b-8394-42c7-8040-522b93c13f5e)

**Comment by amimi818** [comment]
Or, could you add a shortcut to turn on/off the sidebar？

**Comment by Nuked88** [comment]
well Alt + Z is opening/closing the sidebar

**Comment by Nuked88** [comment]
Now the sidebar will open when you hover on the border, and hide when you click outside!

**Comment by amimi818** [comment]
> Now the sidebar will open when you hover on the border, and hide when you click outside!

Great！ thank u very much！
