### ISSUE TITLE
Do not display newly included templates

### ISSUE THREAD

**Issue by HaoJingang** [Nuked88/ComfyUI-N-Sidebar#90]
On the Microsoft Edge browser, if a node template has just been included, refreshing it will not display it, but refreshing it on the Google Chrome browser will display it. Please update this feature.

**Comment by HaoJingang** [comment]
I like this plugin, so I would suggest many areas for improvement. Haha, I hope it will be even more perfect。

**Comment by Steudio** [comment]
I have the same problem with Firefox, I'm not sure from where the plugin is getting the data but if I update a template, the plugin is still dropping the old template (while getting it from the Comfy menu works fine)

**Comment by dahun2** [comment]
I also have the same issue. It appears in Edge, but not in Chrome.

**Comment by Nuked88** [comment]
Hi! Can you try now?

**Comment by dahun2** [comment]
> Hi! Can you try now?

It's working now! nice!
