### ISSUE TITLE
How to import a workflow?

### ISSUE THREAD

**Issue by jokerconnor** [Nuked88/ComfyUI-N-Sidebar#94]
I did not find an entry to import the workflow, only the directory where the workflow was created and I can't find sidebar setting.
Please...

**Comment by Nuked88** [comment]
I've just updated the [README ](https://github.com/Nuked88/ComfyUI-N-Sidebar?tab=readme-ov-file#how-to-set-workflows-folder) since you're not the first to ask this!

**Comment by jokerconnor** [comment]
Thank you!
