### ISSUE TITLE
Hello!I found the conflict Node!!!

### ISSUE THREAD

**Issue by T8mars** [Nuked88/ComfyUI-N-Sidebar#95]
I found the conflict node with N-sidebar,please tell others!!

https://github.com/christian-byrne/comfyui-search-navigation

this node cause the N-sidebar invaild!!I try 300 nodes and found it!

**Comment by Nuked88** [comment]
Thanks! I have slightly modified the code so that it can also coexist with that extension!

**Comment by T8mars** [comment]
Thanks for your work again and again
