### ISSUE TITLE
[BUG] latest commit broke something

### ISSUE THREAD

**Issue by novaexe** [Nuked88/ComfyUI-N-Sidebar#96]
not entirely sure but https://github.com/Nuked88/ComfyUI-N-Sidebar/commit/9c9417622eb0f05bc4f1d56cce0a772f4f94a463 broke the entirety of sidebar

**Comment by novaexe** [comment]
![image](https://github.com/user-attachments/assets/93d79e19-285f-41e0-a258-cefe7fec06f3)

![image](https://github.com/user-attachments/assets/e280d5de-cdb1-410b-a8cc-4f68fa4b96ec)

**Comment by novaexe** [comment]
all nodes/pins are gone will revert to prev commit to check

**Comment by novaexe** [comment]
yes can confirm it's on your end 
![image](https://github.com/user-attachments/assets/4c5642d3-b289-43d8-8de2-915ad984f4a5)

**Comment by Nuked88** [comment]
Uhm, can you show me you developer console? I've just changed a class name, maybe it's just a cache problem? 🤔

**Comment by novaexe** [comment]
> Uhm, can you show me you developer console? I've just changed a class name, maybe it's just a cache problem? 🤔

like for chrome?

**Comment by novaexe** [comment]
it was chromes cache data tyvm

**Comment by camoody1** [comment]
I'm on Microsoft Edge and have cleared my site date for ComfyUI. My list is still broken.
